# syntax=docker/dockerfile:1.4

FROM node:22-alpine

WORKDIR /app

ENV TZ=America/Sao_Paulo \
    NODE_ENV=production \
    PORT=3000

COPY BackEnd/package*.json ./
RUN npm ci --omit=dev && npm install -g sequelize-cli

COPY BackEnd/ ./

EXPOSE 3000

COPY docker/entrypoint.backend.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]