# syntax=docker/dockerfile:1.4

FROM node:22-alpine

WORKDIR /app

ENV TZ=America/Sao_Paulo

COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ ./

EXPOSE 5173

COPY docker/entrypoint.frontend.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
 
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]